In [1]:
import numpy as np

**Given the following matrices:**

```c
A = [[2, -1, 3],
     [0, 4, 1]]
```
```c
B = [[1, 2],
     [-2, 0],
     [5, 3]]
```

**a**. Identify the number of rows and columns in each matrix

**b**. Determine whether the matrices can be multiplied. If so, specify whether it's (AB), (BA), both

**c**. If multiplication is defined, compute the resulting matrix



#### Solutions

In [5]:
# computing both matrices
A = np.array([[2, -1, 3],
              [0, 4, 1]])
B = np.array([[1, 2],
              [-2, 0],
              [5, 3]])

**(a)** answer

**A** has 2 rows and 3 columns, that is **A** is a 2X3 matrice

**B** has 3 rows and 2 columns, that is **B** is a 3X2 matrice

In [7]:
print("The shape of matrice A:", A.shape)
print("The shape of matrice B:", B.shape)

The shape of matrice A: (2, 3)
The shape of matrice B: (3, 2)


**(b)** answer

**A** X **B** = **AB**  is possible because **A** has 3 columns and **B** has 3 rows

**B** X **A** = **BA** is possible because **B** has  2 columns and **A** has 2 rows

**(c)** answer

```c
A = [[2, -1, 3],
     [0, 4, 1]]
B = [[1, 2],
     [-2, 0],
     [5, 3]]
```

```c
AB = [[(2x1 + (-1x-2) + 3x5), (2x2 + (-1x0) + 3x3)],
      [(0x1 + 4x-2 + 1x5), (0x2 + 4x0 + 1x3)]]
AB = [[19, 13],
      [-3   3]]

BA = [[(2x1 + 2x0), (1x-1 + 2x4), (1x3+2x1)],
      [(-2x2 + 0x0), (-2x-1 + 0x4), (-2x3 + 0x1)],
      [[(5x2 + 0x3), (5x-1 + 3x4), (5x3 + 3x1)]]]
BA = [[2, 7, 5],
      [-4, 2, -6],
      [10, 7, 18]]
```

In [12]:
# multiplying matrice A and B
AB = np.dot(A, B)
print(f"AB is:\n{AB}\nThe shape is {AB.shape}")

BA = np.dot(B, A)
print(f"\nBA is:\n{BA}\nThe shape is {BA.shape}")

AB is:
[[19 13]
 [-3  3]]
The shape is (2, 2)

BA is:
[[ 2  7  5]
 [-4  2 -6]
 [10  7 18]]
The shape is (3, 3)
