In [2]:
import numpy as np

In [8]:
# 4 x 4 identity matrix
identity_matrix = np.eye(4)
print("Identity matrix:\n", identity_matrix)

# Replcaing the diagonal with number
np.fill_diagonal(identity_matrix, [10, 20, 30, 40])
print("Diagonal matrix\n", identity_matrix)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix
 [[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]


5. Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)


In [15]:
a_arr = np.random.randint(1, 11, size=(3, 4))
b_arr = np.random.randint(1, 11, size=(4, 3))

# Array product
# product_arr = np.dot(a_arr, b_arr)
# product_arr
product_arr = a_arr @ b_arr
print("Array product\n", product_arr)


Array product
 [[135 217 112]
 [ 55 143  81]
 [134 221  97]]


6. Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1.

In [16]:
def arr_even_sq_odd_minus_1(arr):
    return np.where(arr % 2 == 0, arr **2, -1)

arr = np.random.randint(1, 20, size=(3, 4))
arr_opration = arr_even_sq_odd_minus_1(arr)

print("Array before operation\n", arr)
print("Array after operation\n", arr_opration)

Array before operation
 [[ 8  3 14  7]
 [ 9 18  2 11]
 [18 16 11  6]]
Array after operation
 [[ 64  -1 196  -1]
 [ -1 324   4  -1]
 [324 256  -1  36]]
